[tool.poetry]
name = "bidsmreye"
version = "0.1.0"
description = "bids app based on bidsMReye"
authors = ["Remi Gau <remi.gau@gmail.com>"]
license = "GPL3"

[tool.poetry.dependencies]
python = "^3.8"
pybids = "^0.14.0"
rich = "^11.0.0"
# deepmreye = {git = "https://github.com/DeepMReye/DeepMReye.git"}

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-cov = "pre-commit"
pre-commit = "black"
black = "^21.12b0"
jupyterlab = "^3.2.8"

[tool.black]
line-length = 90

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
