name: Test and coverage

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ "*" ]

jobs:
  test_and_coverage:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ['3.9']

    steps:

    - name: Clone repo
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        pip install .

    - name: Run demo
      run: make demo
